(
// Define quantities
DefineQuantity("ID", "ID", "code"),
DefineQuantity("Code", "code", "string"),
DefineQuantity("Name", "name", "string"),
DefineQuantity("Shortname", "shortname", "string"),
//DefineQuantity("Designator","designator","string"),
DefineQuantity("Descr", "descr", "string"),
DefineQuantity("Comments", "cmnts", "string"),
//DefineQuantity("SPECIFICATION", "spec", "string"),
DefineQuantity("Purpose", "purpose", "string"),
DefineQuantity("Type", "type", "string"),
DefineQuantity("ClCD", "clcd", "string"),
DefineQuantity("GrpClsCD", "grpclscd", "string"),
DefineQuantity("SystemType", "systype", "string"),
DefineQuantity("Diameter", "diam", "mm"),
DefineQuantity("InnerDiam", "inndiam", "mm"),
DefineQuantity("OuterDiam", "outdiam", "mm"),
DefineQuantity("Radius", "radius", "mm"),
DefineQuantity("Thickness", "thickness", "mm"),
DefineQuantity("SequenceNum", "seqnum", "1"),
DefineQuantity("Number", "number", "1"),
DefineQuantity("Factor", "factor", "1"),
DefineQuantity("CurrIndic", "currind", "string"),
DefineQuantity("User", "user", "nvarchar(50)"),
DefineQuantity("Creator", "creator", "string"),
DefineQuantity("Editor", "editor", "string"),
//DefineQuantity("CreaTime", "creatime", "dt"), // creation time
//DefineQuantity("EdiTime", "editime", "dt"), // editing time
//DefineQuantity("InstTime", "insttime", "dt"),
DefineQuantity("XCoord", "xcoord", "1"),
DefineQuantity("YCoord", "ycoord", "1"),
DefineQuantity("ZCoord", "zcoord", "1"),
DefineQuantity("RawGeom", "rawgeom", "bytes"),
DefineQuantity("Geometry", "geometry", "bytes"),
DefineQuantity("Measure", "measure", "m"),
DefineQuantity("Altitude", "altitude", "m"),
DefineQuantity("Money", "money", "1"),
DefineQuantity("Height", "height", "m"),
DefineQuantity("Depth", "depth", "m"),
DefineQuantity("Percent", "perc", "%"),
DefineQuantity("Watercut", "watercut", "%"),
DefineQuantity("Ratio", "ratio", "1"),
DefineQuantity("Width", "width", "1"),
DefineQuantity("Count", "count", "1"),
DefineQuantity("VolRate", "volrate", "m^3/day"),
DefineQuantity("Velocity", "velocity", "m/s"),
DefineQuantity("Comprssblty", "Comprssblty", "1"),
DefineQuantity("GasFactor", "GF", "1"),
DefineQuantity("TimeSpan", "timespan", "day"),
DefineQuantity("Viscosity", "viscosity", "sP"),
DefineQuantity("KinemVisc", "kinevisc", "mm^2/s"),
DefineQuantity("Speed", "speed", "m/s"),
DefineQuantity("RD", "rd", "string"), // symbolic code lookup
DefineQuantity("HRD", "hrd", "string"), // hierarchical  code lookup
DefineQuantity("RC", "rc", "1"), // numeric code lookup
)